### ISSUE TITLE
`cross` is unnecessary for building?

### ISSUE THREAD

**Issue by paavohuhtala** [pixix4/ev3dev-lang-rust#17]
Hi! I just acquired an EV3 kit and wanted to write some Rust for it, and your SDK was exactly what I was looking for. I tried to build a simple Hello World program with your instructions, but I couldn't get `cross` working under WSL2 on Windows. I decided to try Cargo's built-in cross compilation support with [`musl`](https://musl.libc.org/) and LLD, and to my surprise it worked without issue.

Here are the steps I took if you want to add them to the README.

1. Install the compilation target for `armv5te-unknown-linux-musleabi`
```
rustup target add armv5te-unknown-linux-musleabi
```
2. Create `.cargo/config.toml` under your project.
3. Add the following lines to it:

```toml
[build]
target = "armv5te-unknown-linux-musleabi"

[target.armv5te-unknown-linux-musleabi]
linker = "rust-lld"
```

4. `cargo build --release`

And you're done!
